### ISSUE TITLE
Movie.getDetails: The getter 'backdropSizes' was called on null.

### ISSUE THREAD

**Issue by fdietze** [Kerego/tmdb_dart#12]
Hi and thanks for this library!

I just tried to get the Details for "The Matrix" (tmdb id 603) and it throwed the following error:

```
E/flutter (19040): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'backdropSizes' was called on null.
E/flutter (19040): Receiver: null
E/flutter (19040): Tried calling: backdropSizes
E/flutter (19040): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (19040): #1      AssetResolver.getBackdropPath (package:tmdb_dart/src/settings/asset-resolver.dart:13:60)
E/flutter (19040): #2      new Movie.fromJson (package:tmdb_dart/src/models/movie.dart:102:37)
E/flutter (19040): #3      MovieService.getDetails.<anonymous closure> (package:tmdb_dart/src/services/movie-service.dart:139:37)
E/flutter (19040): #4      _CommonService._get (package:tmdb_dart/src/services/common-service.dart:28:20)
E/flutter (19040): <asynchronous suspension>
E/flutter (19040): #5      MovieService.getDetails (package:tmdb_dart/src/services/movie-service.dart:135:12)
```

Be aware that every field form the tmdb API responses might be null/undefined. (https://developers.themoviedb.org/3/movies/get-movie-details)

**Comment by Kerego** [comment]
Based on the stacktrace, it seems that it is not the response that is null but the configuration, I will check it.

**Comment by Kerego** [comment]
This is a bit bizarre, normally you shouldn't be able to access MovieService if the configuration is null.
Do you use the MovieService directly? if yes, you shouldn't. 
The library is supposed to be used through the TmdbService facade and requires a call to 'await InitConfiguration()' to ensure the configuration is loaded correctly.

**Comment by fdietze** [comment]
> Do you use the MovieService directly? if yes, you shouldn't.

Yes, I'm using `MovieService` directly. I didn't know how to use this library since there was no documentation yet.

Now I'm doing:

```dart
    final tmdb = TmdbService(ApiKeys.tmdb);
    // https://developers.themoviedb.org/3/configuration/get-api-configuration
    await tmdb.initConfiguration(); 
    final details = await tmdb.movie.getDetails(apiResult.id);
    print(details.credits.cast.map((c) => c.name).join(", "));
    print(details.credits.crew.map((c) => c.name).join(", "));
```

But `credits` is `null`. What am I doing wrong?

**Comment by Akash98Sky** [comment]
Actually credits are not included in movie details by default. You need to use append settings to include credits and use details.credits

`
final tmdb = TmdbService(ApiKeys.tmdb);
    // https://developers.themoviedb.org/3/configuration/get-api-configuration
    await tmdb.initConfiguration(); 
    final details = await tmdb.movie.getDetails(apiResult.id, appendSettings: AppendSettings(includeCredits: true));
    print(details.credits.cast.map((c) => c.name).join(", "));
    print(details.credits.crew.map((c) => c.name).join(", "));
`

**Comment by fdietze** [comment]
It's working now, thank you!
